'use client';
import comicListener from './comic-listener';
import characterCheers from './character-cheers';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Expand, Grid2X2, Pause, Play, RotateCcw, X, EyeOff, UserRound, FileText, Lightbulb, TriangleAlert, Target, GitFork, CircleCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { chapters, schedule, slides, steps, type Slide } from './slides';
const pad=(n:number)=>String(n).padStart(2,'0');
function Content({s,revealed=false,breakTimer}:{s:Slide;revealed?:boolean;breakTimer?:ReactNode}){
 if(s.kind==='role-dialogue')return <><div className="slide-heading"><span className="eyebrow">{s.tag}</span><h1>{s.title}</h1></div><div className="role-dialogue-grid">{s.items?.map(([role,concerns])=><section key={role}><h2>{role}</h2><p>{concerns}</p></section>)}</div>{s.sub&&<p className="role-dialogue-shared">{s.sub}</p>}<div className="dialogue-closing" aria-hidden={!revealed}><img className="dialogue-cheers" src={characterCheers} alt="ジョッキを持って乾杯する二人のコンセプトキャラクター"/><div className="dialogue-punchline">{s.bottom}</div></div></>;
 if(s.kind==='gherkin-example')return <><div className="slide-heading"><span className="eyebrow">{s.tag}</span><h1>{s.title}</h1></div><section className="gherkin-panel"><span className="gherkin-label">Gherkin記法</span><h2><span>Feature:</span> きゅうりを食べる</h2><p className="gherkin-description"><small># description</small>人がきゅうりを食べるときの振る舞い</p><h3><span>Scenario:</span> 数十本のきゅうりを食べるとお腹が満たされる</h3><div className="gherkin-lines">{s.items?.map(([keyword,text],i)=><div key={keyword}><strong>{keyword}</strong><span className="gherkin-meaning">{['前提','行動','結果'][i]}</span><p>{text}</p></div>)}</div></section><div className="bottom-message">{s.bottom}</div></>;
 if(s.kind==='compact-template')return <><div className="slide-heading"><span className="eyebrow">{s.tag}</span><h1>{s.title}</h1></div><div className="compact-template-grid">{s.items?.map(([question,detail],i)=>{const Icon=[UserRound,Lightbulb,Target,CircleCheck][i];return <section className="compact-template-card" key={question} style={{'--overview-color':['#d5e8ff','#dfebcc','#e3d8f6','#f7d2e7'][i]} as React.CSSProperties}><div className="overview-question"><span>{i+1}</span><h2>{question}</h2></div><div className="overview-icon"><Icon size={42} strokeWidth={1.7}/></div><p>{detail}</p></section>})}</div><section className="template-summary"><h2>まとめ</h2><p>このデザインは、<br/>［誰の］［どんな課題］を解決して［目指す状態］を実現するために、［この方法］を選びました。</p></section></>;
 if(s.kind==='comic-aside')return <div className="comic-aside-content"><div className="comic-exclamation" aria-hidden="true">!?</div><h1>{s.title}</h1><p>{s.sub}</p><img className="comic-listener" src={comicListener} alt="首をかしげて両手を広げる、顔のない線画のコンセプトキャラクター"/></div>;

 if(s.kind==='shared-understanding')return <><div className="slide-heading"><span className="eyebrow">{`${pad(s.chapter+1)} / ${chapters[s.chapter]}`}</span><h1>{s.title}</h1></div><div className="shared-methods">{s.items?.map(([title,description,example],i)=><section className="shared-method" key={title}><span className="method-number">{pad(i+1)}</span><h2>{title}</h2><p>{description}</p>{example&&<div className="method-example">{example}</div>}</section>)}</div><div className="bottom-message">{s.bottom}</div></>;
 if(s.kind==='cover')return <><div className="cover-label"><span>DESIGN / WORDS</span><span>デザインの言語化ワークショップ</span></div><div className="cover-composition"><div className="cover-type"><h1>{s.title.split('\n').map((x,i)=><span key={x} className={i?'yellow':''}>{x}</span>)}</h1><p className="lead">{s.sub}</p></div><div className="reason-poster" aria-hidden="true"><div className="poster-question">WHY<span>?</span></div><div className="poster-label">なぜ選んだかを伝える</div><div className="poster-steps"><span>観察</span><b>↗</b><span>解釈</span><b>↘</b><span>課題</span><b>↗</b><span>比較</span><b>↘</b><span>判断</span></div></div></div><div className="cover-bottom"><span>{s.bottom}</span><span className="cover-edition">THINK. TALK. UPDATE.</span></div></>;
 if(s.kind==='break')return <div className={`break-content ${breakTimer?'has-break-timer':''}`}><span className="eyebrow">休憩</span>{!breakTimer&&<div className="break-mark" aria-hidden="true">PAUSE<span>Ⅱ</span></div>}<h1>{s.title}</h1>{s.sub&&<p className="restart">{s.sub}</p>}<p className="lead">{s.bottom}</p>{breakTimer}</div>;
 return <><div className="slide-heading">{s.kind==='evidence-check'?<div className="evidence-heading-labels"><span className="eyebrow">{s.tag}</span><div className="evidence-mini-bubble">根拠が不足している時は</div></div>:<span className="eyebrow">{s.tag||`${pad(s.chapter+1)} / ${chapters[s.chapter]}`}</span>}{s.kind!=='conversation'&&<h1>{s.title}</h1>}{s.sub&&<p className="lead">{s.sub}</p>}</div>
 {s.kind==='steps-overview'?<div className="seven-overview"><svg className="overview-wrap-arrow" viewBox="0 0 1000 436" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="overview-arrow-tip" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M2 2L8 5L2 8" fill="none" stroke="#8875ad" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></marker></defs><path d="M886 197V210Q886 218 878 218H251Q243 218 243 226V240" fill="none" stroke="#8875ad" strokeWidth="2" markerEnd="url(#overview-arrow-tip)"/></svg>{s.items?.map(([question,en],i)=>{const Icon=[UserRound,FileText,Lightbulb,TriangleAlert,Target,GitFork,CircleCheck][i];return <section className="overview-step" key={en} style={{'--overview-color':['#d5e8ff','#c8eee7','#dfebcc','#ffebbc','#e3d8f6','#ffe0cf','#f7d2e7'][i]} as React.CSSProperties}><div className="overview-question"><span>{i+1}</span><h2>{question}</h2></div><div className="overview-icon"><Icon size={42} strokeWidth={1.7}/></div><p>{en}</p></section>})}</div>:
 s.kind==='role-perspectives'?<div className="perspective-diagram"><svg className="perspective-arrows" viewBox="0 0 900 380" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="perspective-arrowhead" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M2 2L8 5L2 8" fill="none" stroke="#8875ad" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/></marker></defs><g fill="none" stroke="#8875ad" strokeWidth="2.5" strokeLinecap="round" markerEnd="url(#perspective-arrowhead)"><path d="M450 308V184"/><path d="M408 317C370 293 322 254 279 239"/><path d="M492 317C530 293 578 254 621 239"/></g></svg>{s.items?.map(([role,en,description],i)=><section className={`perspective-role perspective-role-${i}`} key={role}><h2>{role}</h2><strong>{en}</strong><p>{description}</p></section>)}<div className="perspective-source">リサーチ結果</div></div>:
 s.kind==='design-layers'?<div className="layer-stack-diagram"><svg className="layer-stack-art" viewBox="0 0 380 340" aria-label="見える層の下に、見えない層がある二層構造" role="img"><g fill="none" stroke="#988da5" strokeWidth="1.5" strokeDasharray="4 5"><path d="M30 103V238M190 30V165M350 103V238M190 176V311"/></g><g opacity="0.55"><path d="M30 238L190 165L350 238L190 311Z" fill="#bca4ec" stroke="#302438" strokeWidth="1.5"/><path d="M30 238L190 311L350 238V247L190 320L30 247Z" fill="#8162bb" stroke="#302438" strokeWidth="1.5"/></g><path d="M30 103L190 30L350 103L190 176Z" fill="#ffdf3d" stroke="#302438" strokeWidth="1.5"/><path d="M30 103L190 176L350 103V112L190 185L30 112Z" fill="#e6b82a" stroke="#302438" strokeWidth="1.5"/><g stroke="#77678d" strokeWidth="1.5"><path d="M350 103H380M350 238H380"/></g></svg><div className="layer-stack-descriptions">{s.items?.map(([label,title,description],i)=><section className={`layer-stack-copy stack-copy-${i}`} key={label}><span>{label}</span><h2>{title}</h2><p>{description}</p></section>)}</div></div>:
 s.kind==='conversation'?<div className={`conversation-layout ${s.items?.length===1?'single':''}`}>{s.items?.map(([role,line,detail],i)=><section className={`speech-turn ${i?'reply':'question'}`} key={role}><div className="speaker-badge"><span aria-hidden="true"><UserRound size={27} strokeWidth={1.8}/></span>{role}</div><div className="speech-bubble"><h2>{line}</h2>{detail&&<p>{detail}</p>}</div></section>)}</div>:
 s.kind==='judgment-gap'?<div className="judgment-diagram"><div className="judgment-chain">{s.items?.map(([label,detail],i)=><div className={`judgment-node ${i>0&&i<5?'unshared':''}`} key={label}><span className="judgment-step">{pad(i+1)}</span><h2>{label}</h2>{detail&&<p>{detail}</p>}</div>)}</div></div>:
 s.kind==='agenda'?<div className="agenda-layout"><div className="schedule">{[schedule.slice(0,7),schedule.slice(7)].map((part,i)=><section key={i}>{part.map(([t,label])=><div key={t} className={label.includes('休憩')?'muted-row':''}><time>{t}</time><span>{label}</span></div>)}</section>)}</div></div>:
 s.kind==='steps'?<><div className="steps-grid">{steps.map(([q,label,en],i)=><div key={q} style={{'--step-color':['#9dccff','#79dac4','#c3a6ff','#f7a6d3','#ffd83d','#bfe37c','#ffa57c'][i]} as React.CSSProperties}><span className="step-num">{i+1}</span><h2>{q}</h2><p>{label}</p><small>{en}</small></div>)}</div><div className="four-questions"><span>01　何が起きている？<small>1–2</small></span><span>02　本当の課題は？<small>3–4</small></span><span>03　どうなればよい？<small>5</small></span><span>04　なぜこの方法？<small>6–7 ＋ 検証</small></span></div></>:
 s.kind==='work'?<div className="work-layout"><div className="work-duration"><span>演習時間</span><strong>{s.time}<small>分</small></strong><p>{s.mode}</p></div><div className="work-instructions">{s.items?.map(([a,b],i)=><div key={a}><span className="instruction-number">{pad(i+1)}</span><section><h2>{a}</h2><p>{b}</p></section></div>)}<div className="done"><strong>完了条件</strong><p>{s.done}</p></div></div></div>:
 s.kind==='search'?<div className="search-demo"><div className="search-bar"><strong>T-Wave</strong><span>住所変更</span><b>検索</b><small>1,360件</small></div><div className="search-results">{s.items?.map(([a,b],i)=><div key={a+i}><span>{pad(i+1)}</span><section><h2>{a}</h2><p>{b}</p></section></div>)}</div><small className="demo-caption">提供資料を再構成した検索結果例</small></div>:
 s.kind==='comparison'?<div className="comparison-table" role="table" aria-label="解決案の比較"><div role="row" className="table-head">{['候補','ユーザーへの効果','実現・運用の制約','まだ未確認のこと'].map(x=><div role="columnheader" key={x}>{x}</div>)}</div>{s.items?.map(row=><div role="row" key={row[0]}>{row.map((cell,i)=><div role="cell" key={i}>{cell}</div>)}</div>)}</div>:
 s.kind==='ui'?<div className="ui-compare"><div><span className="demo-label">BEFORE · 色だけの表示</span><div className="ui-card"><h2>引越しの手続き</h2>{['住所変更','通勤申請','財形貯蓄'].map((x,i)=><div className="mock-row" key={x}>{x}<i className={i===0?'green':'gray'}/></div>)}<p>完了した手続きと、次にすることが分かる？</p></div></div><div><span className="demo-label yellow">AFTER · 手続き名・状態・次の行動</span><div className="ui-card improved"><h2>必要な手続き <small>1 / 3 完了</small></h2><div className="mock-row">住所変更 <b>✓ 完了</b></div><div className="mock-row">通勤申請 <b className="pending">未申請</b></div><div className="mock-row">財形貯蓄 <b className="pending">未確認</b></div><p className="next-action">次に、通勤申請の条件を確認 →</p></div></div></div>:
 s.kind==='sources'?<div className="sources-list">{s.items?.map(([a,b],i)=><div key={a}><strong>{a}</strong><p>{i===2?<a href="https://www.nngroup.com/articles/ten-usability-heuristics/" target="_blank" rel="noreferrer">{b} ↗</a>:i===3?<a href="https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html" target="_blank" rel="noreferrer">{b} ↗</a>:b}</p></div>)}</div>:
 s.kind==='flow'?<div className={`flow-grid count-${s.items?.length}`}>{s.items?.map(([a,b],i)=><div key={a}><span className="flow-number">{pad(i+1)}</span><h2>{a}</h2><p>{b}</p></div>)}</div>:
 s.items?<div className={`cards ${s.kind==='compare'?'compare':''} ${s.kind==='quote'?'quotes':''} count-${s.items.length}`}>{s.items.map(([a,b,c],i)=><div key={a}><span className="card-kicker">{pad(i+1)}</span><h2>{a}</h2><p>{b}</p>{c&&<small>{c}</small>}</div>)}</div>:null}
 {s.bottom&&<div className="bottom-message">{s.bottom}</div>}</>
}
export default function Home(){
 const [index,setIndex]=useState(0),[menu,setMenu]=useState(false),[notes,setNotes]=useState(false),[black,setBlack]=useState(false),[full,setFull]=useState(false),[message,setMessage]=useState('');
 const [seconds,setSeconds]=useState<number|null>(null),[running,setRunning]=useState(false),[timerTitle,setTimerTitle]=useState(''),[timerTotal,setTimerTotal]=useState(0);
 const [dialogueRevealed,setDialogueRevealed]=useState(false);
 useEffect(()=>setDialogueRevealed(false),[index]);
 const deadline=useRef(0),touch=useRef<[number,number]|null>(null); const s=slides[index];
 const go=(n:number)=>{const next=Math.max(0,Math.min(slides.length-1,n));setIndex(next);window.location.hash=`slide-${next+1}`;setMessage('')};
 useEffect(()=>{const read=()=>{const m=window.location.hash.match(/^#slide-(\d+)$/);if(m)setIndex(Math.max(0,Math.min(slides.length-1,Number(m[1])-1)))};read();window.addEventListener('hashchange',read);const f=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',f);return()=>{window.removeEventListener('hashchange',read);document.removeEventListener('fullscreenchange',f)}},[]);
 async function toggleFull(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else setMessage('全画面表示はブラウザの表示メニューから切り替えてください。')}catch{setMessage('全画面表示はブラウザの表示メニューから切り替えてください。')}}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(menu||(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,[contenteditable="true"]')))return;if(black){if(['b','B','Escape',' '].includes(e.key)){e.preventDefault();setBlack(false)}return}if(s.kind==='role-dialogue'&&!dialogueRevealed&&(e.key===' '||e.key==='Enter')&&!(e.target instanceof HTMLElement&&e.target.closest('button,a'))){e.preventDefault();setDialogueRevealed(true);return}if(e.key==='ArrowRight'||e.key==='PageDown'||(e.key===' '&&!(e.target instanceof HTMLElement&&e.target.closest('button,a')))){e.preventDefault();go(index+1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(index-1)}if(e.key==='Home'){e.preventDefault();go(0)}if(e.key==='End'){e.preventDefault();go(slides.length-1)}if(e.key.toLowerCase()==='f'){e.preventDefault();void toggleFull()}if(e.key.toLowerCase()==='b'){e.preventDefault();setBlack(true)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[index,menu,black,dialogueRevealed]);
 useEffect(()=>{if(!running)return;const tick=()=>{const left=Math.max(0,Math.ceil((deadline.current-Date.now())/1000));setSeconds(left);if(left===0)setRunning(false)};tick();const id=window.setInterval(tick,250);return()=>clearInterval(id)},[running]);
 function start(){const total=(s.time||0)*60;setSeconds(total);setTimerTotal(total);setTimerTitle(s.tag||'休憩');deadline.current=Date.now()+total*1000;setRunning(true)}
 function pause(){if(running){setSeconds(Math.max(0,Math.ceil((deadline.current-Date.now())/1000)));setRunning(false)}else if(seconds!==null&&seconds>0){deadline.current=Date.now()+seconds*1000;setRunning(true)}}
 const timerInSlide=s.kind==='break'&&s.timerPlacement==='badge';
 const timerStart=s.time?<Button variant="outline" onClick={start} aria-label={timerInSlide?`${s.time}分のタイマーを開始`:undefined}><Play/>{!timerInSlide&&`${s.time}分を開始`}</Button>:null;
 const timerActions=seconds!==null?<><span className="sr-only" role="status">{seconds===0?'時間です。作業をまとめましょう。':''}</span><Button variant="ghost" onClick={pause} disabled={seconds===0} aria-label={running?'タイマーを一時停止':'タイマーを再開'}>{running?<Pause/>:<Play/>}</Button><Button variant="ghost" onClick={()=>{setRunning(false);setSeconds(timerTotal)}} aria-label="タイマーをリセット"><RotateCcw/></Button><Button variant="ghost" onClick={()=>{setRunning(false);setSeconds(null)}} aria-label="タイマーを閉じる"><X/></Button></>:null;
 const displaySeconds=seconds??(s.time||0)*60;
 const breakTimer=timerInSlide?<section className={`break-timer ${seconds===0?'finished':''}`} aria-label="休憩タイマー"><span className="break-timer-label">{seconds===null?'休憩タイマー':timerTitle}</span><output role="timer" aria-live="off" aria-label="残り時間">{pad(Math.floor(displaySeconds/60))}:{pad(displaySeconds%60)}</output>{timerActions&&<div className="break-timer-actions">{timerActions}</div>}<div className="break-timer-start">{timerStart}</div></section>:undefined;
 return <main className={`workshop ${full?'fullscreen':''}`}><header className="toolbar"><a className="brand" href="#slide-1" aria-label="表紙へ">D<span>/</span>W</a><span className="site-title">デザインの言語化 <span>WORKSHOP</span></span><div className="toolbar-actions"><Button variant="ghost" onClick={()=>setMenu(true)}><Grid2X2/>進行・目次</Button><Button variant="ghost" onClick={()=>{setNotes(!notes)}} aria-pressed={notes}><BookOpen/><span className="button-label">講師メモ</span></Button><Button variant="ghost" onClick={toggleFull} aria-label={full?'全画面を終了':'全画面表示'} title="F：全画面"><Expand/></Button></div></header>
 <div className="progress-track" aria-hidden="true"><div style={{width:`${(index+1)/slides.length*100}%`}}/></div>
 <article className={`slide ${s.kind||'standard'} ${s.chapter===5?'tips':''} ${dialogueRevealed?'dialogue-revealed':''}`} onClick={s.kind==='role-dialogue'?()=>setDialogueRevealed(true):undefined} data-chapter={s.chapter} key={index} aria-label={`${index+1}枚目：${s.title}`} onTouchStart={e=>{touch.current=[e.touches[0].clientX,e.touches[0].clientY]}} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current[0],dy=e.changedTouches[0].clientY-touch.current[1];if(Math.abs(dx)>90&&Math.abs(dx)>Math.abs(dy)*2)go(index+(dx<0?1:-1));touch.current=null}}><Content s={s} revealed={dialogueRevealed} breakTimer={breakTimer}/><div className="slide-folio" aria-hidden="true">{pad(index+1)} <span>/ {slides.length}</span></div></article>
 {notes&&<aside className="speaker-notes"><strong>講師メモ <small>この画面にも表示されます</small></strong><p>{s.note}</p><Button variant="ghost" onClick={()=>setNotes(false)} aria-label="講師メモを閉じる"><X/></Button></aside>}
 <footer className="controls"><div className="chapter-label"><span>{pad(s.chapter+1)}</span><p>{chapters[s.chapter]}<small>← → 移動　 F 全画面　 B 暗転</small></p></div>{!timerInSlide&&<div className="timer-area">{timerStart}{seconds!==null&&<div className={`timer ${seconds===0?'finished':''}`}><span className="timer-context">{timerTitle}</span><output role="timer" aria-live="off" aria-label="残り時間">{pad(Math.floor(seconds/60))}:{pad(seconds%60)}</output>{timerActions}</div>}</div>}<nav aria-label="スライド操作"><Button variant="ghost" onClick={()=>go(index-1)} disabled={index===0} aria-label="前のスライド"><ArrowLeft/></Button><span className="page-count" aria-live="polite">{pad(index+1)}<small> / {slides.length}</small></span><Button onClick={()=>go(index+1)} disabled={index===slides.length-1} aria-label="次のスライド"><ArrowRight/></Button></nav></footer>
 {message&&<p className="status-message" role="status">{message}</p>}
 <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="contents-dialog"><DialogTitle>進行・目次</DialogTitle><DialogDescription>09:00–17:00 ／ 実施390分・休憩90分。選んだスライドから再開できます。</DialogDescription><div className="contents-list">{chapters.map((chapter,c)=><section key={chapter}><h2>{pad(c+1)}　{chapter}</h2>{slides.map((slide,i)=>slide.chapter===c?<button key={i} className={i===index?'current':''} onClick={()=>{go(i);setMenu(false)}} aria-current={i===index?'page':undefined}><span>{pad(i+1)}</span>{slide.title.replaceAll('\n','')}{slide.kind==='work'&&<small>{slide.time}分</small>}</button>:null)}</section>)}</div></DialogContent></Dialog>
 {black&&<div className="blackout" role="dialog" aria-modal="true" aria-label="投影を一時的に暗転中"><Button onClick={()=>setBlack(false)} autoFocus variant="ghost"><EyeOff/>表示を戻す <small> B / Esc</small></Button></div>}
 </main>
}
