'use client';
/* oxlint-disable next/no-img-element -- This slide deck also ships as static GitHub Pages assets without an image optimization server. */
import naikiCharacter from '../public/character-naiki.png?url';
import workingCharacter from '../public/concept-character-working.png?url';
import thinkingCharacter from '../public/concept-character-thinking.png?url';
import conceptCharacter from '../public/concept-character.png?url';
import welcomeCharacter from '../public/concept-character-welcome.png?url';
import karutaCharacters from '../public/concept-character-karuta.png?url';
import caseSearchReference from '../public/case-search-reference.png?url';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Expand, Grid2X2, Pause, Play, RotateCcw, X, EyeOff, UserRound, FileText, Lightbulb, TriangleAlert, Target, GitFork, CircleCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { chapters, schedule, slides, type Slide } from './slides';
const pad=(n:number)=>String(n).padStart(2,'0');
function SlideHeading({s}:{s:Slide}){
 return <div className="slide-heading">{s.tag&&<span className="eyebrow">{s.tag}</span>}<h1>{s.title}</h1>{s.sub&&<p className="lead">{s.sub}</p>}</div>
}
function PhrasedTitle({text}:{text:string}){
 const parts=text.split(/(?<=：)|(?<=！)|(?<=している)|(?<=にて)|(?<=デザインを)|(?<=手続きの)|(?<=席次表を元に)|(?<=席替えを)|(?<=回答を)/).filter(Boolean);
 return <>{parts.map((part,i)=><span className="title-phrase" key={i}>{part}</span>)}</>;
}
function ConceptArt({welcome=false,thinking=false,working=false,className=''}:{welcome?:boolean;thinking?:boolean;working?:boolean;className?:string}){
 return <img className={`concept-art ${welcome?'welcome-art':''} ${className}`} src={working?workingCharacter:thinking?thinkingCharacter:welcome?welcomeCharacter:conceptCharacter} alt="" aria-hidden="true"/>;
}
function Content({s,revealed=false,breakTimer}:{s:Slide;revealed?:boolean;breakTimer?:ReactNode}){
 if(s.kind==='goal')return <><div className="slide-heading">{s.tag&&<span className="eyebrow">{s.tag}</span>}<h1>{s.title}</h1></div><div className="goal-grid">{s.items?.map(([label,detail])=><section key={label}><h2>{label}</h2>{detail&&<p>{detail}</p>}</section>)}</div>{s.bottom&&<div className="bottom-message">{s.bottom}</div>}</>;
 if(s.kind==='transition')return <div className="transition-composition"><div className="transition-copy">{s.tag&&<span className="eyebrow">{s.tag}</span>}<h1><PhrasedTitle text={s.title}/></h1>{s.sub&&<p className="lead">{s.sub}</p>}{s.bottom&&<p className="transition-bottom">{s.bottom}</p>}{s.timeWindow&&<time className="session-time">{s.timeWindow}</time>}</div><div className={`transition-art ${s.illustration==='welcome'?'paper-art':''}`}><ConceptArt welcome={s.illustration==='welcome'} thinking={s.sourceId==='35:1446'} working={s.sourceId==='35:1490'}/></div></div>;
 if(s.kind==='karuta')return <><SlideHeading s={s}/><div className="karuta-scene"><img src={karutaCharacters} alt="二人のコンセプトキャラクターがカルタで遊んでいる様子"/></div>{s.bottom&&<div className="bottom-message">{s.bottom}</div>}</>;
 if(s.kind==='guest')return <div className="guest-composition"><SlideHeading s={{...s,title:s.title.replace(' - ','\n- ')}}/><div className="guest-character"><img src={naikiCharacter} alt="花を持ったサブキャラクター、Naiki"/></div></div>;
 if(s.kind==='reference-image')return <><SlideHeading s={s}/><div className="reference-image-layout"><a href={caseSearchReference} target="_blank" rel="noreferrer" aria-label="検索結果の参考画像を大きく表示"><img src={caseSearchReference} alt="T-Waveで住所変更を検索した結果の参考画像"/></a>{s.callout&&<p className="reference-callout">{s.callout}</p>}</div>{s.bottom&&<div className="bottom-message">{s.bottom}</div>}</>;
 if(s.kind==='hypotheses')return <><SlideHeading s={s}/><div className="hypotheses-diagram"><section className="hypothesis-fact"><h2>{s.items?.[0]?.[0]}</h2><p>{s.items?.[0]?.[1]}</p></section><div className="hypothesis-branches">{s.items?.slice(1).map(([label,text],i)=><section key={label+i}><h2>{label}</h2><p>{text}</p></section>)}</div></div>{s.bottom&&<div className="bottom-message">{s.bottom}</div>}</>;

 if(s.kind==='case-profile')return <><div className="slide-heading"><span className="eyebrow">{s.tag}</span><h1>{s.title}</h1></div><section className="case-situation profile-basic"><h2>基本情報</h2><ul className="profile-facts">{s.items?.map(([fact])=><li key={fact}>{fact}</li>)}</ul></section><section className="profile-goal"><h2>到達したいゴール</h2><p>{s.bottom}</p></section></>;
 if(s.kind==='case')return <><div className="slide-heading"><span className="eyebrow">{s.tag}</span><h1>{s.title}</h1></div>{s.items?.map(([label,situation])=><section className="case-situation" key={label}><h2>{label}</h2><p>{situation}</p></section>)}<p className="case-context">{s.bottom}</p></>;
 if(s.kind==='role-dialogue')return <><div className="slide-heading"><span className="eyebrow">{s.tag}</span><h1>{s.title}</h1></div><div className="role-dialogue-grid">{s.items?.map(([role,concerns])=><section key={role}><h2>{role}</h2><p>{concerns.replace(/(?<=）)\s+(?=どれ|VISION)|(?<=？)\s+(?=システム|SLA)/g,'\n')}</p></section>)}</div>{s.sub&&<p className="role-dialogue-shared">{s.sub.replace(/(?<=ある。)\s+/g,'\n')}</p>}<div className="dialogue-closing" aria-hidden={!revealed}><img className="dialogue-cheers" src={conceptCharacter} alt="相手に話しかけるコンセプトキャラクター"/><div className="dialogue-punchline">{s.bottom}</div></div></>;
 if(s.kind==='gherkin-example')return <><div className="slide-heading"><span className="eyebrow">{s.tag}</span><h1>{s.title}</h1></div><section className="gherkin-panel"><span className="gherkin-label">Gherkin記法</span><h2><span>Feature:</span> きゅうりを食べる</h2><p className="gherkin-description"><small># description</small>人がきゅうりを食べるときの振る舞い</p><h3><span>Scenario:</span> 数十本のきゅうりを食べるとお腹が満たされる</h3><div className="gherkin-lines">{s.items?.map(([keyword,text],i)=><div key={keyword}><strong>{keyword}</strong><span className="gherkin-meaning">{['前提','行動','結果'][i]}</span><p>{text}</p></div>)}</div></section><div className="bottom-message">{s.bottom}</div></>;
 if(s.kind==='compact-template')return <><div className="slide-heading"><span className="eyebrow">{s.tag}</span><h1>{s.title}</h1></div><div className="compact-template-grid">{s.items?.map(([question,detail],i)=>{const Icon=[UserRound,Lightbulb,Target,CircleCheck][i];return <section className="compact-template-card" key={question} style={{'--overview-color':['#d5e8ff','#dfebcc','#e3d8f6','#f7d2e7'][i]} as React.CSSProperties}><div className="overview-question"><span>{i+1}</span><h2>{question}</h2></div><div className="overview-icon"><Icon size={42} strokeWidth={1.7}/></div><p>{detail}</p>{s.callout&&i===3&&<div className="template-callout">{s.callout}</div>}</section>})}</div>{s.summary&&<section className="template-summary"><h2>まとめ</h2><p>{s.summary}</p></section>}{s.bottom&&<div className="bottom-message">{s.bottom}</div>}</>;
 if(s.kind==='comic-aside')return <div className="comic-aside-content"><div className="comic-exclamation" aria-hidden="true">!?</div><h1>{s.title}</h1><p>{s.sub}</p><img className="comic-listener" src={conceptCharacter} alt="考えを伝えるコンセプトキャラクター"/></div>;

 if(s.kind==='shared-understanding')return <><div className="slide-heading"><span className="eyebrow">{s.tag||`${pad(s.chapter+1)} / ${chapters[s.chapter]}`}</span><h1>{s.title}</h1></div><div className="shared-methods">{s.items?.map(([title,description,example],i)=><section className="shared-method" key={title}><span className="method-number">{pad(i+1)}</span><h2>{title}</h2><p>{description}</p>{example&&<div className="method-example">{example}</div>}</section>)}</div><div className="bottom-message">{s.bottom}</div></>;
 if(s.kind==='cover')return <><div className="cover-label"><span>DESIGN / WORDS</span><span>デザインの言語化ワークショップ</span></div><div className="cover-composition"><div className="cover-type"><h1>{s.title.split(s.sourceId==='2:6'?/(?=言語化WS$)/:'\n').map((x,i)=><span key={x} className={i?'yellow':''}>{s.illustration?<PhrasedTitle text={x}/>:x}</span>)}</h1>{s.sub&&<p className="lead">{s.sub}</p>}{s.illustration&&<ConceptArt welcome={s.illustration==='welcome'} className="cover-character"/>}</div><div className="reason-poster" aria-hidden="true"><div className="poster-question">WHY<span>?</span></div><div className="poster-label">なぜ選んだかを伝える</div><div className="poster-steps"><span>観察</span><b>↗</b><span>解釈</span><b>↘</b><span>課題</span><b>↗</b><span>比較</span><b>↘</b><span>判断</span></div></div></div><div className="cover-bottom"><span>{s.bottom}</span><span className="cover-edition">THINK. TALK. UPDATE.</span></div></>;
 if(s.kind==='break')return <div className={`break-content ${breakTimer?'has-break-timer':''}`}>{!breakTimer&&<><span className="eyebrow">休憩</span><div className="break-mark" aria-hidden="true">PAUSE<span>Ⅱ</span></div></>}<h1>{s.title}</h1>{s.sub&&<p className="restart">{s.sub}</p>}{s.bottom&&<p className="lead">{s.bottom}</p>}{s.timeWindow&&s.sourceId!=='2:2805'&&<time className="session-time">{s.timeWindow}</time>}{breakTimer}</div>;
 return <><div className="slide-heading">{s.kind==='evidence-check'?<div className="evidence-heading-labels"><span className="eyebrow">{s.tag}</span><div className="evidence-mini-bubble">根拠が不足している時は</div></div>:<span className="eyebrow">{s.tag||`${pad(s.chapter+1)} / ${chapters[s.chapter]}`}</span>}{s.kind!=='conversation'&&<h1>{s.title}</h1>}{s.sub&&<p className="lead">{s.sub}</p>}</div>
 {s.kind==='steps-overview'?<div className="seven-overview"><svg className="overview-wrap-arrow" viewBox="0 0 1000 436" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="overview-arrow-tip" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M2 2L8 5L2 8" fill="none" stroke="#8875ad" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></marker></defs><path d="M886 197V210Q886 218 878 218H251Q243 218 243 226V240" fill="none" stroke="#8875ad" strokeWidth="2" markerEnd="url(#overview-arrow-tip)"/></svg>{s.items?.map(([question,en],i)=>{const Icon=[UserRound,FileText,Lightbulb,TriangleAlert,Target,GitFork,CircleCheck][i];return <section className="overview-step" key={en} style={{'--overview-color':['#d5e8ff','#c8eee7','#dfebcc','#ffebbc','#e3d8f6','#ffe0cf','#f7d2e7'][i]} as React.CSSProperties}><div className="overview-question"><span>{i+1}</span><h2>{question}</h2></div><div className="overview-icon"><Icon size={42} strokeWidth={1.7}/></div><p>{en}</p></section>})}</div>:
 s.kind==='role-perspectives'?<div className="perspective-diagram"><svg className="perspective-arrows" viewBox="0 0 900 380" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="perspective-arrowhead" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M2 2L8 5L2 8" fill="none" stroke="#8875ad" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/></marker></defs><g fill="none" stroke="#8875ad" strokeWidth="2.5" strokeLinecap="round" markerEnd="url(#perspective-arrowhead)"><path d="M450 308V184"/><path d="M408 317C370 293 322 254 279 239"/><path d="M492 317C530 293 578 254 621 239"/></g></svg>{s.items?.map(([role,en,description],i)=><section className={`perspective-role perspective-role-${i}`} key={role}><h2>{role}</h2><strong>{en}</strong><p>{description}</p></section>)}<div className="perspective-source">リサーチ結果</div></div>:
 s.kind==='design-layers'?<div className="layer-stack-diagram"><svg className="layer-stack-art" viewBox="0 0 380 340" aria-hidden="true"><g fill="none" stroke="#988da5" strokeWidth="1.5" strokeDasharray="4 5"><path d="M30 103V238M190 30V165M350 103V238M190 176V311"/></g><g opacity="0.55"><path d="M30 238L190 165L350 238L190 311Z" fill="#bca4ec" stroke="#302438" strokeWidth="1.5"/><path d="M30 238L190 311L350 238V247L190 320L30 247Z" fill="#8162bb" stroke="#302438" strokeWidth="1.5"/></g><path d="M30 103L190 30L350 103L190 176Z" fill="#ffdf3d" stroke="#302438" strokeWidth="1.5"/><path d="M30 103L190 176L350 103V112L190 185L30 112Z" fill="#e6b82a" stroke="#302438" strokeWidth="1.5"/><g stroke="#77678d" strokeWidth="1.5"><path d="M350 103H380M350 238H380"/></g></svg><div className="layer-stack-descriptions">{s.items?.map(([label,title,description],i)=><section className={`layer-stack-copy stack-copy-${i}`} key={label}><span>{label}</span><h2>{title}</h2><p>{description}</p></section>)}</div></div>:
 s.kind==='conversation'?<div className={`conversation-layout ${s.items?.length===1?'single':''}`}>{s.items?.map(([role,line,detail],i)=><section className={`speech-turn ${i?'reply':'question'}`} key={role}><div className="speaker-badge"><span aria-hidden="true"><UserRound size={27} strokeWidth={1.8}/></span>{role}</div><div className="speech-bubble"><h2>{line}</h2>{detail&&<p>{detail}</p>}</div></section>)}</div>:
 s.kind==='judgment-gap'?<div className="judgment-diagram"><div className="judgment-chain">{s.items?.map(([label,detail],i)=><div className={`judgment-node ${i>0&&i<5?'unshared':''}`} key={label}><span className="judgment-step">{pad(i+1)}</span><h2>{label}</h2>{detail&&<p>{detail}</p>}</div>)}</div></div>:
 s.kind==='agenda'?<div className="agenda-layout"><div className="schedule">{[schedule.slice(0,Math.ceil(schedule.length/2)),schedule.slice(Math.ceil(schedule.length/2))].map((part,i)=><section key={i}>{part.map(([t,label])=><div key={t} className={label.includes('休憩')?'muted-row':''}><time>{t}</time><span>{label}</span></div>)}</section>)}</div></div>:
 s.kind==='work'?<div className="work-layout"><div className="work-duration"><span>演習時間</span><strong>{s.time}<small>分</small></strong>{s.mode&&<p>{s.mode}</p>}{s.timeWindow&&<time className="session-time">{s.timeWindow}</time>}</div><div className="work-instructions">{s.items?.map(([a,b],i)=><div key={a}><span className="instruction-number">{pad(i+1)}</span><section><h2>{a}</h2>{b&&<p>{b}</p>}</section></div>)}{s.done&&<div className="done"><strong>完了条件</strong><p>{s.done}</p></div>}</div></div>:
 s.kind==='flow'?<div className={`flow-grid count-${s.items?.length}`}>{s.items?.map(([a,b],i)=><div key={a}><span className="flow-number">{pad(i+1)}</span><h2>{a}</h2>{b&&<p>{b}</p>}</div>)}</div>:
 s.items?<div className={`cards ${s.kind==='compare'?'compare':''} ${s.kind==='quote'?'quotes':''} count-${s.items.length}`}>{s.items.map(([a,b,c],i)=><div key={a}><span className="card-kicker">{pad(i+1)}</span><h2>{a}</h2>{b&&<p>{b}</p>}{c&&<small>{c}</small>}</div>)}</div>:null}
 {s.bottom&&<div className="bottom-message">{s.bottom}</div>}</>
}
export default function Home(){
 const [index,setIndex]=useState(0),[menu,setMenu]=useState(false),[notes,setNotes]=useState(false),[black,setBlack]=useState(false),[full,setFull]=useState(false),[message,setMessage]=useState('');
 const [seconds,setSeconds]=useState<number|null>(null),[running,setRunning]=useState(false),[timerTitle,setTimerTitle]=useState(''),[timerTotal,setTimerTotal]=useState(0),[timerSlideIndex,setTimerSlideIndex]=useState<number|null>(null);
 const [revealedSlide,setRevealedSlide]=useState<number|null>(null);
 const dialogueRevealed=revealedSlide===index;
 const deadline=useRef(0),touch=useRef<[number,number]|null>(null); const s=slides[index];
 const go=(n:number)=>{const next=Math.max(0,Math.min(slides.length-1,n));setIndex(next);setRevealedSlide(null);window.location.hash=`slide-${next+1}`;setMessage('')};
 useEffect(()=>{const read=()=>{const m=window.location.hash.match(/^#slide-(\d+)$/);if(m){setIndex(Math.max(0,Math.min(slides.length-1,Number(m[1])-1)));setRevealedSlide(null)}};read();window.addEventListener('hashchange',read);const f=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',f);return()=>{window.removeEventListener('hashchange',read);document.removeEventListener('fullscreenchange',f)}},[]);
 async function toggleFull(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else setMessage('全画面表示はブラウザの表示メニューから切り替えてください。')}catch{setMessage('全画面表示はブラウザの表示メニューから切り替えてください。')}}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(menu||(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,[contenteditable="true"]')))return;if(black){if(['b','B','Escape',' '].includes(e.key)){e.preventDefault();setBlack(false)}return}if(s.kind==='role-dialogue'&&!dialogueRevealed&&(e.key===' '||e.key==='Enter')&&!(e.target instanceof HTMLElement&&e.target.closest('button,a'))){e.preventDefault();setRevealedSlide(index);return}if(e.key==='ArrowRight'||e.key==='PageDown'||(e.key===' '&&!(e.target instanceof HTMLElement&&e.target.closest('button,a')))){e.preventDefault();go(index+1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(index-1)}if(e.key==='Home'){e.preventDefault();go(0)}if(e.key==='End'){e.preventDefault();go(slides.length-1)}if(e.key.toLowerCase()==='f'){e.preventDefault();void toggleFull()}if(e.key.toLowerCase()==='b'){e.preventDefault();setBlack(true)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[index,menu,black,dialogueRevealed,s.kind]);
 useEffect(()=>{if(!running)return;const tick=()=>{const left=Math.max(0,Math.ceil((deadline.current-Date.now())/1000));setSeconds(left);if(left===0)setRunning(false)};tick();const id=window.setInterval(tick,250);return()=>clearInterval(id)},[running]);
 function start(){const total=(s.time||0)*60;setSeconds(total);setTimerTotal(total);setTimerSlideIndex(index);setTimerTitle(s.tag||(s.kind==='break'?'休憩':s.title));deadline.current=Date.now()+total*1000;setRunning(true)}
 function pause(){if(running){setSeconds(Math.max(0,Math.ceil((deadline.current-Date.now())/1000)));setRunning(false)}else if(seconds!==null&&seconds>0){deadline.current=Date.now()+seconds*1000;setRunning(true)}}
 const workTimerInSlide=s.kind==='work'&&!!s.time;
 const timerInSlide=workTimerInSlide||(s.kind==='break'&&s.timerPlacement==='badge');
 const timerOnThisSlide=seconds!==null&&timerSlideIndex===index;
 const timerStart=s.time?<Button variant="outline" onClick={start} aria-label={timerInSlide?`${s.time}分のタイマーを開始`:undefined}><Play/>{!timerInSlide&&`${s.time}分を開始`}</Button>:null;
 const timerActions=seconds!==null?<><output className="sr-only">{seconds===0?'時間です。作業をまとめましょう。':''}</output><Button variant="ghost" onClick={pause} disabled={seconds===0} aria-label={running?'タイマーを一時停止':'タイマーを再開'}>{running?<Pause/>:<Play/>}</Button><Button variant="ghost" onClick={()=>{setRunning(false);setSeconds(timerTotal)}} aria-label="タイマーをリセット"><RotateCcw/></Button><Button variant="ghost" onClick={()=>{setRunning(false);setSeconds(null);setTimerSlideIndex(null)}} aria-label="タイマーを閉じる"><X/></Button></>:null;
 const displaySeconds=timerOnThisSlide?seconds!:(s.time||0)*60;
 const breakTimer=timerInSlide?<section className={`break-timer ${workTimerInSlide?'work-timer':''} ${timerOnThisSlide&&seconds===0?'finished':''}`} aria-label={workTimerInSlide?'演習タイマー':'休憩タイマー'}><output role="timer" aria-live="off" aria-label="残り時間">{pad(Math.floor(displaySeconds/60))}:{pad(displaySeconds%60)}</output>{timerOnThisSlide?<div className="break-timer-actions">{timerActions}</div>:<div className="break-timer-start">{timerStart}</div>}</section>:undefined;
 return <main className={`workshop ${full?'fullscreen':''}`}><header className="toolbar"><a className="brand" href="#slide-1" aria-label="表紙へ">D<span>/</span>W</a><span className="site-title">デザインの言語化 <span>WORKSHOP</span></span><div className="toolbar-actions"><Button variant="ghost" onClick={()=>setMenu(true)}><Grid2X2/>進行・目次</Button><Button variant="ghost" onClick={()=>{setNotes(!notes)}} aria-pressed={notes}><BookOpen/><span className="button-label">講師メモ</span></Button><Button variant="ghost" onClick={toggleFull} aria-label={full?'全画面を終了':'全画面表示'} title="F：全画面"><Expand/></Button></div></header>
 <div className="progress-track" aria-hidden="true"><div style={{width:`${(index+1)/slides.length*100}%`}}/></div>
 <article className={`slide ${s.kind||'standard'} ${s.illustration?'with-character':''} ${s.sourceId==='2:3887'||s.sourceId==='35:2431'?'closing-cover':''} ${dialogueRevealed?'dialogue-revealed':''}`} data-chapter={s.chapter} data-source={s.sourceId} data-work={s.tag?.match(/WORK\s*([12])/i)?.[1]} data-break={s.sourceId==='2:2169'?'lunch':s.sourceId==='2:2805'?'afternoon':undefined} key={index} aria-label={`${index+1}枚目：${s.title}`} onTouchStart={e=>{touch.current=[e.touches[0].clientX,e.touches[0].clientY]}} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current[0],dy=e.changedTouches[0].clientY-touch.current[1];if(Math.abs(dx)>90&&Math.abs(dx)>Math.abs(dy)*2)go(index+(dx<0?1:-1));touch.current=null}}><Content s={s} revealed={dialogueRevealed} breakTimer={workTimerInSlide?undefined:breakTimer}/>{workTimerInSlide&&breakTimer}{s.kind==='role-dialogue'&&!dialogueRevealed&&<button className="dialogue-reveal-trigger" onClick={()=>setRevealedSlide(index)} aria-label="対話についてのメッセージを表示"/>}<div className="slide-folio" aria-hidden="true">{pad(index+1)} <span>/ {slides.length}</span></div></article>
 {notes&&<aside className="speaker-notes"><strong>講師メモ <small>この画面にも表示されます</small></strong><p>{s.note}</p><Button variant="ghost" onClick={()=>setNotes(false)} aria-label="講師メモを閉じる"><X/></Button></aside>}
 <footer className="controls"><div className="chapter-label"><span>{pad(s.chapter+1)}</span><p>{chapters[s.chapter]}<small>← → 移動　 F 全画面　 B 暗転</small></p></div>{(!timerInSlide||(seconds!==null&&!timerOnThisSlide))&&<div className="timer-area">{!timerInSlide&&timerStart}{seconds!==null&&<div className={`timer ${seconds===0?'finished':''}`}><span className="timer-context">{timerTitle}</span><output role="timer" aria-live="off" aria-label="残り時間">{pad(Math.floor(seconds/60))}:{pad(seconds%60)}</output>{timerActions}</div>}</div>}<nav aria-label="スライド操作"><Button variant="ghost" onClick={()=>go(index-1)} disabled={index===0} aria-label="前のスライド"><ArrowLeft/></Button><span className="page-count" aria-live="polite">{pad(index+1)}<small> / {slides.length}</small></span><Button onClick={()=>go(index+1)} disabled={index===slides.length-1} aria-label="次のスライド"><ArrowRight/></Button></nav></footer>
 {message&&<output className="status-message">{message}</output>}
 <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="contents-dialog"><DialogTitle>進行・目次</DialogTitle><DialogDescription>09:00–17:00 ／ 実施390分・休憩90分。選んだスライドから再開できます。</DialogDescription><div className="contents-list">{chapters.map((chapter,c)=><section key={chapter}><h2>{pad(c+1)}　{chapter}</h2>{slides.map((slide,i)=>slide.chapter===c?<button key={i} className={i===index?'current':''} onClick={()=>{go(i);setMenu(false)}} aria-current={i===index?'page':undefined}><span>{pad(i+1)}</span>{slide.title.replaceAll('\n','')}{slide.kind==='work'&&<small>{slide.time}分</small>}</button>:null)}</section>)}</div></DialogContent></Dialog>
 {black&&<dialog open className="blackout" aria-modal="true" aria-label="投影を一時的に暗転中"><Button onClick={()=>setBlack(false)} autoFocus variant="ghost"><EyeOff/>表示を戻す <small> B / Esc</small></Button></dialog>}
 </main>
}
